#!/bin/sh

#clean up
rm -rf obj_dir
rm -rf riscvpipe.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall -Wno-UNUSEDSIGNAL --cc --trace riscvpipe.sv --exe riscvpipe_simple_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vriscvpipe.mk Vriscvpipe

# run executable simulation file
obj_dir/Vriscvsingle
