#!/bin/sh

#clean up
rm -rf obj_dir
rm -rf RiscVCPU.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace RiscVCPU.sv --exe RiscVCPU_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VRiscVCPU.mk VRiscVCPU

# run executable simulation file
obj_dir/VRiscVCPU
